
kind: Namespace
apiVersion: v1
metadata:
  name: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: tftest/flask
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: flask
  namespace: flask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  tls:
    - hosts:
        - flask.com
  rules:
    - host: flask.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: flask
              servicePort: 5000